### ISSUE TITLE
Class 'Grav\Plugin\BetterCommentsPlugin' does not have a method 'onFormProcessed'

### ISSUE THREAD

**Issue by vlp-git** [AizkibelRojo/grav-bettercomments#1]
Hello,

I just added `{% include 'partials/bettercomments.html.twig' %}` into the post template and i got a crash:

```
TypeError
Failed to create closure from callable: class 'Grav\Plugin\BetterCommentsPlugin' does not have a method 'onFormProcessed'
```

If u have any idea !

Tks !!

**Comment by AizkibelRojo** [comment]
Hi @vlp-git ,

Be sure that you have enabled te plugin on admin panel.

You can add a conditional load on twig using this code:
`{% if config.plugins.bettercomments.enabled %}
    {% include 'partials/bettercomments.html.twig'
{% endif %}`

On bettercomments.php line 22 and 23 remove comment and set enabled to false

You can find this changes on this [commit](https://github.com/AizkibelRojo/grav-bettercomments/commit/c542d0784c9a05b4521333cf59eae853bbfb5b47)


If this work please say me and i would update the plugin to v1.0.3
