### ISSUE TITLE
Emails generated but comments not stored (via Discourse)

### ISSUE THREAD

**Issue by hughbris** [AizkibelRojo/grav-bettercomments#19]
I'm reporting what seems to be an issue which is well described on Discourse by a user who is not on Github:

> [Better Comments plugin sends email but doesn’t post comments](https://discourse.getgrav.org/t/better-comments-plugin-sends-email-but-doesnt-post-comments/21937)

**Comment by AizkibelRojo** [comment]
> I'm reporting what seems to be an issue which is well described on Discourse by a user who is not on Github:
> 
> > [Better Comments plugin sends email but doesn’t post comments](https://discourse.getgrav.org/t/better-comments-plugin-sends-email-but-doesnt-post-comments/21937)

Thank, I will see how to replicate and solve the issue.

**Comment by AizkibelRojo** [comment]
Issue related to squeleton no to this plugin
