### ISSUE TITLE
"Pages" in admin is empty after installing the plugin

### ISSUE THREAD

**Issue by MikeEchoVoid** [AizkibelRojo/grav-bettercomments#6]
Hi, 
the plugin is working fine even the captcha but "pages" in the admin area is empty and I can't modify or add a new page. When I desactivate the plugin, I can see all see all my pages is the admin area.

Can you help me please.

thanks.

**Comment by AizkibelRojo** [comment]
Hi @MikeEchoVoid 
Can yo give me error logs from PHP, apache/nginx or other sources to debug what is happen.

Please tell me what theme and plugins do you have installed, I will try to replicate your Grav enviroment.

In site that I have it installed I´m not having any issue.
